name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  ENTRY_FILE: main.go
  FUNCTION_NAME: domytest
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go get .
    
      - name: Building Code
        run: |
          GOOS=linux GOARCH=amd64 go build -o main main.go lambda_response_writer.go
          zip deployment.zip main

      - name: Check if lambda exists
        id: lambda_status
        continue-on-error: true
        run: aws lambda get-function --function-name ${{ env.FUNCTION_NAME }} > /dev/null 2>&1
         
      - name: Create Function
        if: steps.lambda_status.outcome != 'success'
        run: |
          aws lambda create-function \
          --function-name ${{ env.FUNCTION_NAME }} \
          --zip-file fileb://deployment.zip \
          --handler main \
          --runtime go1.x \
          --role ${{ secrets.AWS_ROLE }} \
          --environment Variables={MONGOSTRING=${{ secrets.MONGOSTRING }}}

      - name: Update Function
        if: steps.lambda_status.outcome == 'success'
        run: aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --zip-file fileb://deployment.zip > /dev/null 2>&1
